/**
 * Svarg — the data a delivered application starts with
 *
 * A customer opening their application for the first time should see it work.
 * An empty database answers "no students are at risk" in the confident voice
 * of a finding, which is worse than useless: it is wrong in a way that reads
 * as right.
 *
 * Aria has already generated representative samples for the datasets the
 * customer has not collected yet (services/syntheticDatasetService.js). Those
 * ship with the project as ordinary CSV files, and the seed script loads them
 * the same way it would load a real export.
 *
 * ── Why this does not break Eame's rule 7 ──────────────────────────────────
 *
 * "Do not invent data. A seed script must read a file the customer supplies"
 * is about the application never fabricating records at runtime, and it holds:
 * nothing here is generated by the delivered code, which reads a file like any
 * other. What changed is that the project now ships with a file.
 *
 * The guarantee that matters is that nobody mistakes a generated figure for
 * their own number, so the labelling is carried end to end and is not
 * cosmetic:
 *   - every row already carries _source=sample, from Aria
 *   - the file is named .sample.csv and sits under data/samples/
 *   - README_DATA.md says what these are and how to replace them
 *   - the prompt requires the application to say so on screen
 *
 * A customer's real upload is not touched: only datasets whose sourceType is
 * 'synthetic' are shipped, so a dataset they actually provided is theirs and
 * ships as itself.
 */

import LinkedProjectDocument from '../models/LinkedProjectDocument.js';

/** `Attendance Log Records` -> `attendance-log-records` */
function slug(name) {
  return String(name || 'dataset').toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'dataset';
}

/**
 * The sample CSVs for a blueprint, as project files.
 *
 * @returns {Promise<{path: string, content: string}[]>} empty when Aria
 *   generated nothing — a project with no samples is a project that seeds
 *   nothing, not an error.
 */
export async function sampleDataFiles(blueprintId) {
  const docs = await LinkedProjectDocument
    .find({ blueprintId, sourceType: 'synthetic' })
    .select('datasetName rawText synthetic').lean()
    .catch(() => []);

  const files = [];
  const seen = new Set();
  const index = [];

  for (const d of docs) {
    const csv = String(d.rawText || '').trim();
    // A dataset that generated nothing is skipped rather than shipped empty:
    // a zero-row CSV seeds nothing and looks like a bug in the seed script.
    if (!csv) continue;

    let name = slug(d.datasetName);
    while (seen.has(name)) name += '-2';
    seen.add(name);

    files.push({ path: `data/samples/${name}.sample.csv`, content: csv + '\n' });
    index.push({
      name: d.datasetName || name,
      file: `data/samples/${name}.sample.csv`,
      rows: d.synthetic?.rowCount ?? (csv.split('\n').length - 1),
    });
  }

  if (!files.length) return [];

  files.push({ path: 'data/README_DATA.md', content: readme(index) });
  // The same index as data, for the application's own Data page: which
  // datasets it was built on, their files, and the columns each expects --
  // the shape the customer's own file is matched onto when they import it.
  files.push({
    path: 'data/datasets.json',
    content: JSON.stringify(index.map(d => {
      const csv = files.find(f => f.path === d.file)?.content || '';
      const header = csv.split('\n')[0] || '';
      return { name: d.name, slug: d.file.replace(/^data\/samples\//, '').replace(/\.sample\.csv$/, ''), file: d.file, sampleRows: d.rows, columns: splitCsvLine(header) };
    }), null, 2) + '\n',
  });
  return files;
}

/** One CSV line into cells, quotes honoured. */
function splitCsvLine(line) {
  const out = []; let cur = ''; let q = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (q) {
      if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') q = false;
      else cur += ch;
    } else if (ch === '"') q = true;
    else if (ch === ',') { out.push(cur.trim()); cur = ''; }
    else cur += ch;
  }
  out.push(cur.trim());
  return out;
}

function readme(index) {
  return [
    '# The data this application starts with',
    '',
    'These files are **sample data**. They were generated to show the shape of',
    'datasets that had not been collected yet — the right columns, plausible',
    'values, the right cardinality. They are evidence of STRUCTURE, never of fact.',
    '',
    'Nothing here describes anything that happened. Do not report a number from',
    'these files as your own.',
    '',
    '| Dataset | File | Rows |',
    '| --- | --- | --- |',
    ...index.map(d => `| ${d.name} | \`${d.file}\` | ${d.rows} |`),
    '',
    '## Replacing them with your own',
    '',
    'Every row carries a `_source` column set to `sample`. Your own export will',
    'not have that column, which is how the application tells the two apart and',
    'why it stops calling itself a demonstration once you load real data.',
    '',
    'Open the application, go to Data (the owner key is on your Svarg go-live',
    'screen), and import your file: the columns are matched to these, the rows',
    'replace the sample, and the application stops calling itself a',
    'demonstration by itself. Or put your export in this directory with the',
    'same columns and run the seed script for that dataset.',
    '',
  ].join('\n');
}
